version: '2.3'
services:
  tftracer:
    user: tf
    container_name: tftracer
    image: laruen/tensorflow:latest
    runtime: nvidia
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - '~/.Xauthority:/home/tf/.Xauthority:rw'
      - '~/tftracer:/home/tf/tftracer'
      - '~/.gitconfig:/home/tf/.gitconfig'
      - './vscodeDotConfig:/home/tf/.vscode'
      - './vscodeGlobalConfig:/home/tf/.config/Code'
      - './fishConfig:/home/tf/.config/fish'
    network_mode: host
    stdin_open: true
    tty: true
